### ISSUE TITLE
Dynamic allocation of executors requires the external shuffle service

### ISSUE THREAD

**Issue by freeshow** [apache/incubator-celeborn#1357]
### Describe the intention you'd like
A clear and concise description of what you want to do.
when I use celeborn, run spark-sql,  exception:
23/03/17 14:43:30 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
Exception in thread "main" org.apache.spark.SparkException: Dynamic allocation of executors requires the external shuffle service. You may enable this through spark.shuffle.service.enabled.
        at org.apache.spark.ExecutorAllocationManager.validateSettings(ExecutorAllocationManager.scala:215)
        at org.apache.spark.ExecutorAllocationManager.<init>(ExecutorAllocationManager.scala:135)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:632)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:54)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>(SparkSQLCLIDriver.scala:328)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:160)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by waitinfuture** [comment]
Hi, to enable dra with celeborn, you should apply the [patch](https://github.com/apache/incubator-celeborn/tree/main/assets/spark-patch) to spark

**Comment by FMX** [comment]
Hi there is a patch needs to apply to your spark distribution.

https://github.com/apache/incubator-celeborn/tree/branch-0.2/assets/spark-patch

**Comment by freeshow** [comment]
> Hi, to enable dra with celeborn, you should apply the [patch](https://github.com/apache/incubator-celeborn/tree/main/assets/spark-patch) to spark

Thanks
